spring.application.name: springboot-jooq


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: mysecretpassword
  flyway:
    enabled: true

logging:
  level:
    org:
      jooq: debug
